

trigger: none
#- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module -Name MicrosoftPowerBIMgmt -Force -AllowClobber
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/eramus_report.pbix'  # Replace with the actual path to your .pbix file
    artifact: 'pbixArtifact'
    publishLocation: 'pipeline'      
- task: DownloadPipelineArtifact@2
  inputs:
    artifact: 'pbixArtifact'
    targetPath: '$(Pipeline.Workspace)'   


- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Variables
      $tenantId = "835f6712-aeca-416a-8b76-d4dad8d12381"
      $clientId = "cdd1cb32-8cea-4768-b972-5f937c78cfe8"
      $clientSecret = "O.g8Q~xTDTFlObwGm75fqkRRIDLr8pNDp1I45crQ"  # Securely store the secret in pipeline variables
      $workspaceId = "17e6dcd9-6633-40e1-bb3a-274e5f1520d9"
      $filePath = "$(Pipeline.Workspace)/eramus_report.pbix"

      # Check if the .pbix file exists
      if (-Not (Test-Path $filePath)) {
        Write-Error "File not found at path: $filePath"
        exit 1
      }

      # Authenticate with Azure AD
      $body = @{
        grant_type    = "client_credentials"
        client_id     = $clientId
        client_secret = $clientSecret
        resource      = "https://analysis.windows.net/powerbi/api"
      }
      
      $tokenResponse = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$tenantId/oauth2/token" -Method Post -ContentType "application/x-www-form-urlencoded" -Body $body
      $accessToken = $tokenResponse.access_token

      # Prepare headers
      $headers = @{
        Authorization = "Bearer $accessToken"
      }

      # API URL for importing the .pbix file
      $uri = "https://api.powerbi.com/v1.0/myorg/groups/$workspaceId/imports?datasetDisplayName=eramusreport"

      # Open the .pbix file as a byte array
      $fileContent = [System.IO.File]::ReadAllBytes($filePath)

      # Upload the .pbix file
      try {
        $response = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $fileContent -ContentType "application/octet-stream"
        Write-Host "Upload successful: $response"
      } catch {
        Write-Error "Failed to upload file: $_"
      }
  displayName: 'Publish Power BI Report'