
trigger: none
#- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      Install-Module -Name MicrosoftPowerBIMgmt -Force -AllowClobber



steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Variables
      $tenantId = "your-tenant-id"
      $clientId = "your-client-id"
      $clientSecret = "$(PowerBIClientSecret)"  # Securely stored as a pipeline variable
      $workspaceId = "your-workspace-id"
      $filePath = "$(Pipeline.Workspace)/your-report.pbix"

      # Check if the .pbix file exists
      if (-Not (Test-Path $filePath)) {
        Write-Error "File not found at path: $filePath"
        exit 1
      }

      # Authenticate with Azure AD
      $body = @{
        grant_type    = "client_credentials"
        client_id     = $clientId
        client_secret = $clientSecret
        resource      = "https://analysis.windows.net/powerbi/api"
      }
      
      $tokenResponse = Invoke-RestMethod -Uri "https://login.microsoftonline.com/$tenantId/oauth2/token" -Method Post -ContentType "application/x-www-form-urlencoded" -Body $body
      $accessToken = $tokenResponse.access_token

      # Prepare headers
      $headers = @{
        Authorization = "Bearer $accessToken"
      }

      # API URL for importing the .pbix file
      $uri = "https://api.powerbi.com/v1.0/myorg/groups/$workspaceId/imports?datasetDisplayName=YourReportName"

      # Open the .pbix file as a byte array
      $fileContent = [System.IO.File]::ReadAllBytes($filePath)

      # Upload the .pbix file
      try {
        $response = Invoke-RestMethod -Uri $uri -Method Post -Headers $headers -Body $fileContent -ContentType "application/octet-stream"
        Write-Host "Upload successful: $response"
      } catch {
        Write-Error "Failed to upload file: $_"
      }
  displayName: 'Publish Power BI Report'